[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "sans serif"

[server]
maxUploadSize = 10
enableCORS = true
maxMessageSize = 200

[browser]
gatherUsageStats = false